apiVersion: v1
kind: Namespace
metadata:
  name: movie-box-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie-box
  namespace: movie-box-system
spec:
  replicas: 1
  selector:
    matchLabels:
      run: movie-box-server
  template:
    metadata:
      labels:
        run: movie-box-server
    spec:
      containers:
        - name: movie-box
          image: ghcr.io/sithumonline/movie-box:0.0.4
          args: ["server"]
          volumeMounts:
            - mountPath: /root/Downloads/movie-box
              name: movie-box-downloads
      volumes:
        - name: movie-box-downloads
          hostPath:
            path: /movie-box
---
apiVersion: v1
kind: Service
metadata:
  name: movie-box-entrypoint
  namespace: movie-box-system
spec:
  type: NodePort
  selector:
    run: movie-box-server
  ports:
    - port: 3080
      targetPort: 3080
      nodePort: 30880
